= crcep.github.io
:nofooter:
:docinfo1:

image:https://img.shields.io/github/stars/crcep?label=Stars%20from%20users&style=social[GitHub Repo stars,link="https://github.com/crcep"]

image::https://avatars.githubusercontent.com/u/83579804[CRC logo, 250, float="left"]

The Corporate Readiness Certificate is an educational program launched in 2014.

Companies operating in the Silesian region in Poland implemented this program in close cooperation with the academic community and Universities. Cooperating companies deal with broadly understood services of the IT industry.

The CRC program offers active students who are open to acquiring new knowledge and practical skills, which provides unique opportunities for professional development.
The CRC program gives the possibility to gain additional specialist knowledge in IT and work management systems in large enterprises, learn about new areas of business activity, and increase the chances of participants on the labor market!

=== Business partners
- https://www.accenture.com[Accenture],
- https://www.ey.com[EY],
- https://www.kyndryl.com[Kyndryl],
- https://inghubspoland.com/en[ING Hubs Poland]

=== streams

==== 2023

- https://crcep.github.io/cybersecurity[Cybersecurity]